/**
 * Original preset place list — no copyrighted assets.
 * Add or remove places freely; the list is sampled at random each round.
 */
export const PRESET_PLACES = [
  'Airport Terminal',
  'Antarctic Research Station',
  'Art Museum',
  'Bank Vault',
  'Beach Resort',
  'Border Checkpoint',
  'Cable Car',
  'Casino Floor',
  'Coal Mine',
  'Coral Reef',
  'Cruise Ship',
  'Dentist Office',
  'Desert Oasis',
  'Embassy',
  'Farmhouse',
  'Fire Station',
  'Floating Market',
  'Hospital',
  'Hotel Lobby',
  'Ice Cream Parlor',
  'Jail Cell',
  'Library',
  'Lighthouse',
  'Military Base',
  'Movie Theater',
  'Night Market',
  'Observatory',
  'Oil Rig',
  'Orphanage',
  'Police Station',
  'Pottery Studio',
  'Radio Station',
  'Restaurant Kitchen',
  'Rock Concert Venue',
  'Ski Lodge',
  'Space Station',
  'Sports Stadium',
  'Submarine',
  'Supermarket',
  'Train Station',
  'University Campus',
  'Volcano Research Base',
  'Wedding Venue',
  'Wildlife Safari',
  'Yoga Studio',
  'Zoo',
];
